//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../grammar/AWSIMScriptGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAWSIMScriptGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AWSIMScriptGrammarBaseListener : IAWSIMScriptGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.scenario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScenario([NotNull] AWSIMScriptGrammarParser.ScenarioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.scenario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScenario([NotNull] AWSIMScriptGrammarParser.ScenarioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] AWSIMScriptGrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] AWSIMScriptGrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.assignmentStm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentStm([NotNull] AWSIMScriptGrammarParser.AssignmentStmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.assignmentStm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentStm([NotNull] AWSIMScriptGrammarParser.AssignmentStmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] AWSIMScriptGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] AWSIMScriptGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] AWSIMScriptGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] AWSIMScriptGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] AWSIMScriptGrammarParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] AWSIMScriptGrammarParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.arrayExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayExp([NotNull] AWSIMScriptGrammarParser.ArrayExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.arrayExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayExp([NotNull] AWSIMScriptGrammarParser.ArrayExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.positionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositionExp([NotNull] AWSIMScriptGrammarParser.PositionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.positionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositionExp([NotNull] AWSIMScriptGrammarParser.PositionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.lanePositionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLanePositionExp([NotNull] AWSIMScriptGrammarParser.LanePositionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.lanePositionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLanePositionExp([NotNull] AWSIMScriptGrammarParser.LanePositionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.routeExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRouteExp([NotNull] AWSIMScriptGrammarParser.RouteExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.routeExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRouteExp([NotNull] AWSIMScriptGrammarParser.RouteExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.variableExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableExp([NotNull] AWSIMScriptGrammarParser.VariableExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.variableExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableExp([NotNull] AWSIMScriptGrammarParser.VariableExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AWSIMScriptGrammarParser.spawnDelayOptionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpawnDelayOptionExp([NotNull] AWSIMScriptGrammarParser.SpawnDelayOptionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AWSIMScriptGrammarParser.spawnDelayOptionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpawnDelayOptionExp([NotNull] AWSIMScriptGrammarParser.SpawnDelayOptionExpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
